### ISSUE TITLE
Enable Helm after macOS re-install

### ISSUE THREAD

**Issue by reysillo** [thunkli/Helm#8]
Hello  guys,

I have 2 partitions in my mac, first one for macOS and the  other one for personal files. 
Yesterday after macOS and helm re-instalation the apps doesn't apply the changes on hosts file, when I try to change the profile I have two  error message:

- getBookmarkWithNSURL
- startAccessingSecurityScopedResource

I think that it could be related with permissions in the new macOS but the app doesn't show any other notification.

 _macOS Catalina 10.15 (19A512f)_

**Comment by reysillo** [comment]
![image](https://user-images.githubusercontent.com/4564010/61717319-75e7d180-ad26-11e9-801e-7d159ee143e7.png)
![image](https://user-images.githubusercontent.com/4564010/61717334-7d0edf80-ad26-11e9-97e3-bb878074160c.png)

**Comment by thunkli** [comment]
Maybe your file `/private/etc/hosts` doesn't exist ?

**Comment by reysillo** [comment]
thanks @thunkli, 

the file is there and have the correct content from before macOS re install, please check the log
<img width="1589" alt="Screen Shot 2019-07-26 at 8 28 12 AM" src="https://user-images.githubusercontent.com/4564010/61954829-5bf4fb80-af7f-11e9-8150-9465a069b13e.png">

**Comment by thunkli** [comment]
Temporarily unable to solve, you can use gasmask https://github.com/2ndalpha/gasmask

**Comment by reysillo** [comment]
OK, thanks , gasmask works well!
