### ISSUE TITLE
Getting errors "getBookmarkWithNSURL" and "startAccessingSecurityScopedResource"

### ISSUE THREAD

**Issue by Designbase** [thunkli/Helm#9]
Getting errors after osx updates when switching from development scheme to Default scheme to :
getBookmarkWithNSURL
and
startAccessingSecurityScopedResource

Any ideas?

**Comment by thunkli** [comment]
You can use gasmask https://github.com/2ndalpha/gasmask

**Comment by Designbase** [comment]
Goi it thanks again
